### ISSUE TITLE
Providing a link for the PDF version of the book

### ISSUE THREAD

**Issue by Omcsesz** [zkoss/zk-mvvm-book#8]
Hello, Team!

I would like to know if someone can provide a link to a pdf version of this book,

**Comment by jeanher** [comment]
Hi!

PDF files are available on the ZK website:
https://www.zkoss.org/documentation#References  ( MVVM book is the second one)

**Comment by Omcsesz** [comment]
Thank you!

Can it be made available without registration?

**Comment by jeanher** [comment]
Regarding registration, it's not only for the download. Once you have a zk account, you can access more resources like asking questions in ZK Forum and reporting issues in ZK Tracker. So why not?

**Comment by Omcsesz** [comment]
Yes, but if I want to login from a different computer, it is easier if I can access the pdf without registration.
